[package]
name = "z2-staging"
version = "0.1.0"
authors = ["Youssef Habri <youssef.habri@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "z2-anilist",
    "z2-config",
    "z2-database",
    "z2-menu"
]

[dependencies]
anilist = { path = "./z2-anilist" }
menu = { path = "./z2-menu" }

async-trait = "0.1"
chrono = "0.4"
env_logger = "0.7"
futures = "0.3"
kankyo = "0.3"
log = "0.4"
lazy_static = "1.4"
serenity = "0.9"
regex = "1.4"
# reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pickledb = "0.4"

[dependencies.tokio]
version = "0.2"
features = ["macros"]
