[package]
name = "z2-staging"
version = "0.1.0"
authors = ["Youssef Habri <youssef.habri@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "z2-anilist"
]

[dependencies]
anilist = { path = "./z2-anilist" }
async-trait = "0.1"
env_logger = "0.7"
futures = "0.3"
kankyo = "0.3"
log = "0.4"
lazy_static = "1.4"
serenity = "0.9.0-rc.2"
regex = "1.4"
# reqwest = "0.9"
# serde = "1.0"
# serde_derive = "1.0"
# serde_json = "1.0"

[dependencies.tokio]
version = "0.2"
features = ["macros"]
